#!/bin/sh
# POSTINST script for victronbtlelogger

echo "\033[36m HI I'M A POSTINST SCRIPT `date +"%s"` \033[39m"
systemctl daemon-reload
systemctl enable victronbtlelogger.service
systemctl start victronbtlelogger.service

exit 0