#!/bin/sh
# POSTINST script for victronbtlelogger

echo "\033[36m HI I'M A POSTINST SCRIPT `date --rfc-3339='seconds'` running as \033[91m`whoami`\033[39m"
adduser --system --ingroup www-data victronbtlelogger
mkdir --verbose --mode 0755 --parents /var/log/victronbtlelogger /var/cache/victronbtlelogger /var/www/html/victronbtlelogger
chown --changes --recursive victronbtlelogger:www-data /var/log/victronbtlelogger /var/cache/victronbtlelogger /var/www/html/victronbtlelogger
chmod --changes --recursive 0644 /var/log/victronbtlelogger/* /var/cache/victronbtlelogger/* /var/www/html/victronbtlelogger/*
systemctl daemon-reload
systemctl enable victronbtlelogger.service
systemctl start victronbtlelogger.service

exit 0
