#!/bin/sh
# PRERM script for victronbtlelogger

echo "\033[36m HI I'M A PRERM SCRIPT `date +"%s"` \033[39m"
systemctl stop victronbtlelogger.service
systemctl disable victronbtlelogger.service

exit 0