#!/bin/sh
# PRERM script for victronbtlelogger

echo "\033[36m PRERM SCRIPT ${0} `date --rfc-3339='seconds'` running as \033[91m`whoami`\033[39m"
systemctl stop victronbtlelogger.service
systemctl disable victronbtlelogger.service

exit 0
